name: Demo Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print message
        run: echo "Hello from GitHub Actions!"
